services:

  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Shanghai
      PROJECT_NAME: ${PROJECT_NAME}
      API_VERSION: ${API_VERSION}
      API_V1_STR: ${API_V1_STR}
      ENVIRONMENT: ${ENVIRONMENT}

      FRONTEND_HOST: ${FRONTEND_HOST?Variable not set}

      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}

      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY?Variable not set}
      
      LOG_FILE_PATH: ${LOG_FILE_PATH}


    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/utils/health-check/"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    build:
      context: ./

volumes:
  app-db-data:
