services:
  db:
    restart: "no"
    ports:
      - "5432:5432"

  api:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./
          action: sync
          target: /app
          ignore:
            - .venv
        - path: ./pyproject.toml
          action: rebuild
    environment:
      ENVIRONMENT: local
      LOG_FILE_PATH: service-dev.log
